import { StyleSheet } from "react-native";
import type { AppThemeColors } from "../theme/colors";

export function createListDetailStyles(c: AppThemeColors) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: c.background,
    },
    staticChrome: {
      flexShrink: 0,
    },
    listBody: {
      flex: 1,
      minHeight: 0,
    },
    listEmptyWrap: {
      marginTop: 60,
      alignItems: "center",
      paddingHorizontal: 24,
      gap: 8,
    },
    listEmptyTitle: {
      marginTop: 2,
      fontSize: 28,
      fontWeight: "700",
      color: c.textTertiary,
    },
    listEmptyText: {
      fontSize: 14,
      color: c.placeholder,
      textAlign: "center",
    },
    loader: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.background,
    },
    topBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 8,
      marginBottom: 6,
    },
    topDeleteBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: c.inputBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
    },
    back: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 8,
      width: 88,
    },
    backText: {
      fontSize: 16,
      fontWeight: "600",
      color: c.text,
    },
    listTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: 17,
      fontWeight: "800",
      color: c.text,
    },
    priceSwitch: {
      flexShrink: 0,
    },
    bulkModalRoot: {
      flex: 1,
      backgroundColor: c.overlayStrong,
      justifyContent: "center",
      paddingHorizontal: 20,
    },
    bulkModalCard: {
      backgroundColor: c.card,
      borderRadius: 20,
      padding: 20,
      maxHeight: "88%",
      shadowColor: c.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 8 },
      elevation: 12,
      overflow: "hidden",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    bulkHero: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.card,
      opacity: 1,
    },
    bulkHeroBlobA: {
      position: "absolute",
      top: -80,
      right: -70,
      width: 220,
      height: 180,
      borderRadius: 90,
      backgroundColor: c.primary,
      opacity: 0.18,
      transform: [{ rotate: "-22deg" }],
    },
    bulkHeroBlobB: {
      position: "absolute",
      bottom: -90,
      left: -80,
      width: 240,
      height: 200,
      borderRadius: 100,
      backgroundColor: c.micIcon,
      opacity: 0.08,
      transform: [{ rotate: "18deg" }],
    },
    bulkModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
      gap: 4,
      justifyContent: "space-between",
    },
    bulkHeaderPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: c.micFabBase,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.micFabBorder,
    },
    bulkHeaderPillText: {
      fontSize: 12,
      fontWeight: "800",
      color: c.text,
      letterSpacing: 0.2,
    },
    bulkHeaderActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    bulkHeaderIconBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: c.inputBg,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    bulkModalTitle: {
      fontSize: 22,
      fontWeight: "900",
      color: c.text,
      marginTop: 2,
    },
    bulkModalHint: {
      fontSize: 14,
      color: c.textTertiary,
      lineHeight: 20,
      marginTop: 6,
      marginBottom: 14,
    },
    bulkFormatCard: {
      borderRadius: 16,
      padding: 14,
      backgroundColor: c.inputBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      gap: 6,
      marginBottom: 16,
    },
    bulkFormatLine: {
      fontSize: 14,
      fontWeight: "800",
      color: c.text,
    },
    bulkFormatSub: {
      fontSize: 12,
      color: c.textTertiary,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.6,
      textAlign: "center",
      opacity: 0.9,
    },
    bulkMicOuter: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: c.bulkMicBg,
      borderWidth: 3,
      borderColor: c.bulkMicBorder,
      alignSelf: "center",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      shadowColor: c.shadow,
      shadowOpacity: 0.14,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 10,
    },
    bulkMicOuterActive: {
      backgroundColor: c.bulkMicActiveBg,
      borderColor: c.bulkMicActiveBorder,
    },
    bulkMicOuterDisabled: {
      opacity: 0.65,
    },
    bulkMicFill: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.bulkMicBg,
    },
    bulkMicOctagon: {
      position: "absolute",
      width: 72,
      height: 72,
      borderRadius: 18,
      backgroundColor: c.bulkMicBorder,
      opacity: 0.24,
      transform: [{ rotate: "22deg" }],
      alignSelf: "center",
    },
    bulkMicBlobA: {
      position: "absolute",
      top: -18,
      right: -16,
      width: 76,
      height: 60,
      borderRadius: 30,
      backgroundColor: c.primary,
      opacity: 0.22,
      transform: [{ rotate: "-18deg" }],
    },
    bulkMicBlobB: {
      position: "absolute",
      bottom: -22,
      left: -18,
      width: 80,
      height: 66,
      borderRadius: 34,
      backgroundColor: c.micIcon,
      opacity: 0.16,
      transform: [{ rotate: "16deg" }],
    },
    bulkStatusLabel: {
      textAlign: "center",
      marginTop: 14,
      fontSize: 15,
      fontWeight: "700",
      color: c.textSecondary,
    },
    bulkTranscriptScroll: {
      maxHeight: 160,
      marginTop: 14,
      backgroundColor: c.bulkTranscriptBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.bulkTranscriptBorder,
    },
    bulkTranscriptText: {
      padding: 12,
      fontSize: 15,
      color: c.text,
      lineHeight: 22,
    },
    bulkErrorText: {
      marginTop: 12,
      fontSize: 13,
      color: c.danger,
      lineHeight: 18,
    },
    totalCard: {
      marginHorizontal: 16,
      marginTop: 2,
      marginBottom: 12,
      backgroundColor: c.totalBg,
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 18,
      borderWidth: 1,
      borderColor: c.totalBorder,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    totalLabel: {
      fontSize: 14,
      fontWeight: "700",
      color: c.totalLabel,
    },
    totalValueInline: {
      fontSize: 22,
      fontWeight: "900",
      color: c.totalValue,
      flexShrink: 1,
    },
    fabBarWrap: {
      position: "absolute",
      left: 16,
      right: 16,
      zIndex: 20,
    },
    fabBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    fabPriceToggle: {
      flex: 1,
      minWidth: 0,
      backgroundColor: c.fabSurface,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      shadowColor: c.shadow,
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    fabPriceToggleLabel: {
      fontSize: 15,
      fontWeight: "700",
      color: c.fabLabel,
      marginRight: 8,
    },
    fabIconBtn: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: c.micFabBg,
      borderWidth: 1.5,
      borderColor: c.micFabBorder,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      shadowColor: c.shadow,
      shadowOpacity: 0.14,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 5 },
      elevation: 6,
    },
    fabMicGradientBase: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.micFabBase,
    },
    fabMicGradientAccentA: {
      position: "absolute",
      top: -14,
      right: -8,
      width: 40,
      height: 32,
      borderRadius: 16,
      backgroundColor: c.micFabAccentA,
      opacity: 0.5,
      transform: [{ rotate: "-20deg" }],
    },
    fabMicGradientAccentB: {
      position: "absolute",
      bottom: -16,
      left: -10,
      width: 42,
      height: 36,
      borderRadius: 18,
      backgroundColor: c.micFabAccentB,
      opacity: 0.32,
      transform: [{ rotate: "18deg" }],
    },
    fabMicInnerRing: {
      position: "absolute",
      left: 6,
      right: 6,
      top: 6,
      bottom: 6,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: c.micFabRing,
    },
    fabPrimaryBtn: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: c.primaryDark,
      shadowOpacity: 0.24,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6,
    },
    errorText: {
      marginHorizontal: 16,
      marginBottom: 6,
      color: c.danger,
      fontSize: 13,
    },
    modalRoot: {
      flex: 1,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: c.overlay,
      justifyContent: "flex-end",
    },
    modalScrollView: {
      flex: 1,
    },
    modalScroll: {
      padding: 16,
    },
    modalCard: {
      backgroundColor: c.card,
      borderRadius: 18,
      padding: 16,
      gap: 12,
      shadowColor: c.shadow,
      shadowOpacity: 0.12,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: -4 },
      elevation: 8,
    },
    modalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 4,
    },
    trashBtn: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: c.trashBg,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: c.trashBorder,
    },
    trashPlaceholder: {
      width: 44,
      height: 44,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: c.text,
      flex: 1,
      textAlign: "center",
    },
    modalClose: {
      width: 44,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    modalForm: {
      gap: 10,
    },
    modalTopControls: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    bulkFromAddBtn: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: c.micFabBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.micFabBorder,
    },
    bulkFromAddBtnText: {
      fontSize: 13,
      fontWeight: "700",
      color: c.micIcon,
    },
    modalPriceToggleInline: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: c.fabSurface,
      borderRadius: 999,
      paddingLeft: 10,
      paddingRight: 6,
      paddingVertical: 4,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    modalPriceToggleInlineText: {
      fontSize: 13,
      fontWeight: "700",
      color: c.fabLabel,
    },
    addRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    unitLabel: {
      fontSize: 13,
      fontWeight: "700",
      color: c.textTertiary,
      width: 36,
    },
    unitInput: {
      width: "100%",
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 11,
      fontSize: 14,
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
    },
    unitSelectBtn: {
      width: "100%",
      minHeight: 42,
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: c.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    unitSelectText: {
      fontSize: 14,
      color: c.text,
      fontWeight: "600",
    },
    unitInlineWrap: {
      flex: 1,
      minWidth: 0,
    },
    addRowSecond: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flexWrap: "wrap",
    },
    addName: {
      flex: 1,
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 16,
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
    },
    qtyStepperShell: {
      flexDirection: "row",
      alignItems: "stretch",
      backgroundColor: c.inputBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      overflow: "hidden",
    },
    qtyStepperShellGrow: {
      flex: 1,
      minWidth: 0,
    },
    qtyStepperShellCompact: {
      flex: 2,
      minWidth: 0,
    },
    qtyStepperShellNarrow: {
      flex: 1.35,
      minWidth: 0,
    },
    qtyStepBtn: {
      width: 44,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: c.stepperBtnBg,
    },
    qtyStepBtnLeft: {
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: c.border,
    },
    qtyStepBtnRight: {
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderLeftColor: c.border,
    },
    qtyStepBtnDisabled: {
      opacity: 0.55,
    },
    qtyStepInput: {
      flex: 1,
      minWidth: 36,
      paddingVertical: 12,
      paddingHorizontal: 6,
      fontSize: 16,
      color: c.text,
      textAlign: "center",
      backgroundColor: c.inputBg,
    },
    addPriceRow: {
      flex: 3,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    priceFieldShell: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.inputBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      overflow: "hidden",
    },
    priceFieldInput: {
      flex: 1,
      minWidth: 0,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 16,
      color: c.text,
    },
    priceFieldCurrencyBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderLeftColor: c.borderMuted,
      backgroundColor: c.stepperBtnBg,
    },
    priceFieldCurrencyText: {
      fontSize: 14,
      fontWeight: "800",
      color: c.text,
    },
    currencyModalRoot: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: c.overlay,
    },
    currencyListCard: {
      backgroundColor: c.card,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      paddingHorizontal: 16,
      paddingTop: 14,
      maxHeight: 480,
    },
    currencyListTitle: {
      fontSize: 17,
      fontWeight: "800",
      color: c.text,
    },
    currencyListHint: {
      fontSize: 12,
      color: c.textTertiary,
      marginTop: 4,
      marginBottom: 8,
    },
    currencyFlatList: {
      maxHeight: 400,
    },
    currencyListRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    currencyListRowActive: {
      backgroundColor: c.currencyActiveRow,
      marginHorizontal: -8,
      paddingHorizontal: 8,
      borderRadius: 10,
    },
    currencyListSymbol: {
      fontSize: 18,
      fontWeight: "800",
      color: c.text,
      width: 40,
    },
    currencyListLabel: {
      flex: 1,
      fontSize: 15,
      color: c.textSecondary,
    },
    micBtn: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: c.accentBlueSoft,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: c.accentBlueBorder,
    },
    addBtn: {
      marginTop: 4,
      backgroundColor: c.primary,
      borderRadius: 14,
      minHeight: 44,
      paddingVertical: 10,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    addBtnText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "800",
    },
    saveBtn: {
      marginTop: 4,
      backgroundColor: c.saveGreen,
      borderRadius: 14,
      minHeight: 44,
      paddingVertical: 10,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    saveBtnText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "800",
    },
    submitRowCompact: {
      marginTop: 4,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    submitRowUnitWrap: {
      flex: 1,
      minWidth: 0,
    },
    unitSelectBtnCompact: {
      width: "100%",
      minHeight: 44,
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: c.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    unitInputCompact: {
      width: "100%",
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 14,
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
    },
    addBtnCompact: {
      flex: 1.35,
      backgroundColor: c.primary,
      borderRadius: 14,
      minHeight: 44,
      paddingVertical: 10,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    saveBtnCompact: {
      flex: 1.35,
      backgroundColor: c.saveGreen,
      borderRadius: 14,
      minHeight: 44,
      paddingVertical: 10,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    unitOptionText: {
      flex: 1,
      fontSize: 16,
      color: c.text,
      fontWeight: "700",
    },
    sectionLabel: {
      marginHorizontal: 16,
      marginTop: 8,
      marginBottom: 6,
      fontSize: 13,
      fontWeight: "800",
      color: c.textTertiary,
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    row: {
      marginHorizontal: 16,
      marginBottom: 10,
      backgroundColor: c.card,
      borderRadius: 14,
      paddingVertical: 10,
      paddingHorizontal: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      shadowColor: c.shadow,
      shadowOpacity: 0.04,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    rowCheckbox: {
      position: "absolute",
      left: -6,
      top: -6,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: c.card,
      borderWidth: 1.2,
      borderColor: c.borderMuted,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 5,
    },
    rowBulkTapOverlay: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 14,
      zIndex: 4,
    },
    rowCardTapOverlay: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 14,
      zIndex: 1,
    },
    rowCheckboxActive: {
      backgroundColor: c.primaryDark,
      borderColor: c.primaryDark,
    },
    rowMuted: {
      opacity: 0.55,
    },
    handle: {
      width: 24,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 3,
    },
    rowTap: {
      flex: 1,
      minWidth: 0,
      paddingRight: 4,
      gap: 4,
      zIndex: 2,
    },
    rowTitleLine: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      minWidth: 0,
    },
    qtyInlineText: {
      fontSize: 14,
      fontWeight: "800",
      color: c.textSecondary,
    },
    qtyDivider: {
      width: StyleSheet.hairlineWidth,
      alignSelf: "stretch",
      backgroundColor: c.borderMuted,
    },
    itemNameText: {
      fontSize: 16,
      fontWeight: "700",
      color: c.text,
      flex: 1,
      minWidth: 0,
    },
    rowMeta: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flexWrap: "wrap",
    },
    metaText: {
      fontSize: 14,
      color: c.textTertiary,
      fontWeight: "600",
    },
    priceLineInline: {
      fontSize: 14,
      flexShrink: 1,
      minWidth: 0,
    },
    priceWithSymbol: {
      fontWeight: "700",
      color: c.text,
    },
    lineTotalInline: {
      fontWeight: "600",
      color: c.textTertiary,
      fontSize: 13,
    },
    strikeText: {
      textDecorationLine: "line-through",
    },
    actionCol: {
      width: 126,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 6,
      zIndex: 3,
    },
    unitMetaText: {
      fontSize: 11,
      fontWeight: "400",
      color: c.textTertiary,
      maxWidth: 42,
    },
    starBtn: {
      width: 22,
      height: 22,
      alignItems: "center",
      justifyContent: "center",
    },
    checkBtn: {
      backgroundColor: c.primaryDark,
      paddingVertical: 10,
      paddingHorizontal: 4,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      minWidth: 0,
    },
    checkText: {
      color: "#fff",
      fontWeight: "900",
      fontSize: 10,
      letterSpacing: 0.2,
    },
    undoBtn: {
      backgroundColor: c.warningOrange,
      paddingVertical: 10,
      paddingHorizontal: 4,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    undoText: {
      color: "#fff",
      fontWeight: "800",
      fontSize: 10,
    },
    uncheckBtn: {
      backgroundColor: c.micIcon,
      paddingVertical: 10,
      paddingHorizontal: 2,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    uncheckText: {
      color: "#fff",
      fontWeight: "800",
      fontSize: 10,
    },
    bulkActionsFloating: {
      position: "absolute",
      left: 16,
      right: 16,
      flexDirection: "row",
      justifyContent: "center",
      gap: 12,
      zIndex: 30,
    },
    bulkOverlayFade: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 15,
      overflow: "hidden",
    },
    bulkOverlayStop: {
      flex: 1,
    },
    bulkCircleBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.card,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      shadowColor: c.shadow,
      shadowOpacity: 0.05,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    bulkCircleBtnDanger: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.trashBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.trashBorder,
    },
  });
}
