/** Preset currencies for the list-level symbol picker (code is stable; symbol is what we store). */
export const CURRENCY_OPTIONS: { code: string; symbol: string; label: string }[] = [
  { code: "PHP", symbol: "₱", label: "Philippine peso (₱)" },
  { code: "USD", symbol: "$", label: "US dollar ($)" },
  { code: "EUR", symbol: "€", label: "Euro (€)" },
  { code: "GBP", symbol: "£", label: "British pound (£)" },
  { code: "JPY", symbol: "¥", label: "Japanese yen (¥)" },
  { code: "CNY", symbol: "¥", label: "Chinese yuan (¥)" },
  { code: "INR", symbol: "₹", label: "Indian rupee (₹)" },
  { code: "KRW", symbol: "₩", label: "Korean won (₩)" },
  { code: "AUD", symbol: "A$", label: "Australian dollar (A$)" },
  { code: "CAD", symbol: "C$", label: "Canadian dollar (C$)" },
  { code: "CHF", symbol: "CHF", label: "Swiss franc (CHF)" },
  { code: "SEK", symbol: "kr", label: "Swedish krona (kr)" },
  { code: "NOK", symbol: "kr", label: "Norwegian krone (kr)" },
  { code: "MXN", symbol: "MX$", label: "Mexican peso (MX$)" },
  { code: "BRL", symbol: "R$", label: "Brazilian real (R$)" },
  { code: "ZAR", symbol: "R", label: "South African rand (R)" },
  { code: "AED", symbol: "د.إ", label: "UAE dirham" },
  { code: "SAR", symbol: "﷼", label: "Saudi riyal" },
  { code: "SGD", symbol: "S$", label: "Singapore dollar (S$)" },
  { code: "HKD", symbol: "HK$", label: "Hong Kong dollar (HK$)" },
  { code: "NZD", symbol: "NZ$", label: "New Zealand dollar (NZ$)" },
  { code: "TRY", symbol: "₺", label: "Turkish lira (₺)" },
  { code: "PLN", symbol: "zł", label: "Polish złoty (zł)" },
  { code: "THB", symbol: "฿", label: "Thai baht (฿)" },
  { code: "IDR", symbol: "Rp", label: "Indonesian rupiah (Rp)" },
  { code: "MYR", symbol: "RM", label: "Malaysian ringgit (RM)" },
  { code: "VND", symbol: "₫", label: "Vietnamese dong (₫)" },
];
