/** List-themed words for faint onboarding background scribble effect. */
export const ONBOARDING_BACKGROUND_WORDS = [
  "milk",
  "eggs",
  "bread",
  "rice",
  "coffee",
  "bananas",
  "tomatoes",
  "onions",
  "yogurt",
  "butter",
  "cheese",
  "chicken",
  "groceries",
  "lunch",
  "dinner",
  "snacks",
  "soap",
  "vitamins",
  "batteries",
  "paper towels",
  "call mom",
  "dentist",
  "pay rent",
  "water plants",
  "walk dog",
  "team meeting",
  "buy gifts",
  "pick up Rx",
  "oil change",
  "laundry",
  "dishes",
  "vacuum",
  "reminder",
  "todo",
  "notes",
  "list",
  "check",
  "done",
] as const;

/** How many words animate at once on the username screen. */
export const ONBOARDING_FLOATING_WORD_COUNT = 10;
