export type AppThemeColors = {
  background: string;
  backgroundElevated: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  border: string;
  borderMuted: string;
  card: string;
  primary: string;
  primaryDark: string;
  danger: string;
  shadow: string;
  overlay: string;
  overlayStrong: string;
  inputBg: string;
  stepperBtnBg: string;
  totalBg: string;
  totalBorder: string;
  totalLabel: string;
  totalValue: string;
  fabSurface: string;
  fabLabel: string;
  micFabBg: string;
  micFabBorder: string;
  micFabBase: string;
  micFabAccentA: string;
  micFabAccentB: string;
  micFabRing: string;
  bulkMicBg: string;
  bulkMicBorder: string;
  bulkMicActiveBg: string;
  bulkMicActiveBorder: string;
  bulkTranscriptBg: string;
  bulkTranscriptBorder: string;
  currencyActiveRow: string;
  trashBg: string;
  trashBorder: string;
  success: string;
  saveGreen: string;
  accentBlueSoft: string;
  accentBlueBorder: string;
  warningOrange: string;
  pin: string;
  historyBtnBg: string;
  placeholder: string;
  switchTrackOff: string;
  switchTrackOn: string;
  switchThumbOn: string;
  switchThumbOff: string;
  iosSwitchBg: string;
  micIcon: string;
  linkBlue: string;
};

export const lightColors: AppThemeColors = {
  background: "#f4f6f8",
  backgroundElevated: "#ffffff",
  text: "#0f172a",
  textSecondary: "#334155",
  textTertiary: "#64748b",
  border: "#e2e8f0",
  borderMuted: "#cbd5e1",
  card: "#ffffff",
  primary: "#2563eb",
  primaryDark: "#1d4ed8",
  danger: "#dc2626",
  shadow: "#0f172a",
  overlay: "rgba(15,23,42,0.45)",
  overlayStrong: "rgba(15,23,42,0.5)",
  inputBg: "#f8fafc",
  stepperBtnBg: "#f1f5f9",
  totalBg: "#ecfdf3",
  totalBorder: "#bbf7d0",
  totalLabel: "#166534",
  totalValue: "#14532d",
  fabSurface: "#ffffff",
  fabLabel: "#0f172a",
  micFabBg: "#fff2e8",
  micFabBorder: "#fdba74",
  micFabBase: "#fff7ed",
  micFabAccentA: "#fdba74",
  micFabAccentB: "#fb923c",
  micFabRing: "rgba(255,255,255,0.8)",
  bulkMicBg: "#eff6ff",
  bulkMicBorder: "#bfdbfe",
  bulkMicActiveBg: "#fef2f2",
  bulkMicActiveBorder: "#fecaca",
  bulkTranscriptBg: "#f8fafc",
  bulkTranscriptBorder: "#e2e8f0",
  currencyActiveRow: "#eff6ff",
  trashBg: "#fef2f2",
  trashBorder: "#fecaca",
  success: "#16a34a",
  saveGreen: "#15803d",
  accentBlueSoft: "#eff6ff",
  accentBlueBorder: "#dbeafe",
  warningOrange: "#f97316",
  pin: "#e8a0a0",
  historyBtnBg: "#ffffff",
  placeholder: "#94a3b8",
  switchTrackOff: "#d1d5db",
  switchTrackOn: "#93c5fd",
  switchThumbOn: "#2563eb",
  switchThumbOff: "#ffffff",
  iosSwitchBg: "#d1d5db",
  micIcon: "#c2410c",
  linkBlue: "#2563eb",
};

export const darkColors: AppThemeColors = {
  background: "#0b1220",
  backgroundElevated: "#111827",
  text: "#f8fafc",
  textSecondary: "#cbd5e1",
  textTertiary: "#94a3b8",
  border: "#334155",
  borderMuted: "#475569",
  card: "#1e293b",
  primary: "#60a5fa",
  primaryDark: "#2563eb",
  danger: "#f87171",
  shadow: "#000000",
  overlay: "rgba(0,0,0,0.62)",
  overlayStrong: "rgba(0,0,0,0.68)",
  inputBg: "#334155",
  stepperBtnBg: "#475569",
  totalBg: "rgba(34,197,94,0.14)",
  totalBorder: "rgba(74,222,128,0.35)",
  totalLabel: "#86efac",
  totalValue: "#bbf7d0",
  fabSurface: "#1e293b",
  fabLabel: "#f8fafc",
  micFabBg: "#431407",
  micFabBorder: "#c2410c",
  micFabBase: "#451a03",
  micFabAccentA: "#ea580c",
  micFabAccentB: "#fb923c",
  micFabRing: "rgba(255,255,255,0.18)",
  bulkMicBg: "#1e3a5f",
  bulkMicBorder: "#3b82f6",
  bulkMicActiveBg: "#450a0a",
  bulkMicActiveBorder: "#f87171",
  bulkTranscriptBg: "#1e293b",
  bulkTranscriptBorder: "#334155",
  currencyActiveRow: "rgba(37,99,235,0.28)",
  trashBg: "#450a0a",
  trashBorder: "#7f1d1d",
  success: "#22c55e",
  saveGreen: "#16a34a",
  accentBlueSoft: "rgba(37,99,235,0.22)",
  accentBlueBorder: "#3b82f6",
  warningOrange: "#fb923c",
  pin: "#fda4af",
  historyBtnBg: "#1e293b",
  placeholder: "#94a3b8",
  switchTrackOff: "#475569",
  switchTrackOn: "rgba(96,165,250,0.45)",
  switchThumbOn: "#60a5fa",
  switchThumbOff: "#e2e8f0",
  iosSwitchBg: "#475569",
  micIcon: "#fb923c",
  linkBlue: "#60a5fa",
};
